### ISSUE TITLE
PDF upload

### ISSUE THREAD

**Issue by AnshulBasia** [umccoin/umc-api#20]
While filing a claim, make the "upload document" button work by transferring the pdf file to remote databse, somehow.

**Comment by AnshulBasia** [comment]
@dlackey  Are you familiar with sending a pdf over a server to a remote database ? Currently, there's just pdf upload button when one files a claim, but we need to store that pdf in our database. I looked it up but couldn't find much.

**Comment by dlackey** [comment]
Note to self: https://coderwall.com/p/7tpa8w/file-upload-with-meteor-method
